// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechWayFit.ContentOS.Infrastructure.Persistence.Postgres;

#nullable disable

namespace TechWayFit.ContentOS.Infrastructure.Persistence.Postgres.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260102093538_UpdateToSnakeCase")]
    partial class UpdateToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechWayFit.ContentOS.Infrastructure.Persistence.Entities.ContentItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("default_language");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("WorkflowStatus")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_status");

                    b.HasKey("Id");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("ix_content_items_content_type");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_content_items_created_at");

                    b.HasIndex("WorkflowStatus")
                        .HasDatabaseName("ix_content_items_workflow_status");

                    b.HasIndex("TenantId", "SiteId", "Environment")
                        .HasDatabaseName("ix_content_items_tenant");

                    b.ToTable("content_items", (string)null);
                });

            modelBuilder.Entity("TechWayFit.ContentOS.Infrastructure.Persistence.Entities.ContentLocalizationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("fields_json");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_content_localizations_language");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_content_localizations_slug");

                    b.HasIndex("ContentItemId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_content_localizations_unique");

                    b.ToTable("content_localizations", (string)null);
                });

            modelBuilder.Entity("TechWayFit.ContentOS.Infrastructure.Persistence.Entities.WorkflowStateRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("current_status");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("integer")
                        .HasColumnName("previous_status");

                    b.Property<DateTimeOffset>("TransitionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transitioned_at");

                    b.Property<Guid?>("TransitionedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("transitioned_by");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_states_content_item");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("ix_workflow_states_current_status");

                    b.ToTable("workflow_states", (string)null);
                });

            modelBuilder.Entity("TechWayFit.ContentOS.Infrastructure.Persistence.Entities.ContentLocalizationRow", b =>
                {
                    b.HasOne("TechWayFit.ContentOS.Infrastructure.Persistence.Entities.ContentItemRow", "ContentItem")
                        .WithMany("Localizations")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("TechWayFit.ContentOS.Infrastructure.Persistence.Entities.ContentItemRow", b =>
                {
                    b.Navigation("Localizations");
                });
#pragma warning restore 612, 618
        }
    }
}
